adopcion/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Home, name='home'),
    path('adoptivo/', include('apps.adoptivo.urls')),
    path('historia/', include('apps.historia.urls',namespace='historia')),
    path('propietario/', include('apps.propietario.urls')),
    path('mascota/', include('apps.mascota.urls',namespace='mascota')),
    path('usuario/', include('apps.usuario.urls',namespace='usuario')),

] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

apps/historia/urls.py
from django.urls import path
from . import views

app_name='historia'
urlpatterns = [
    path('index/', views.index, name="index"),
    path('addHistorias/', views.addHistoria, name="addHistorias"),
    path('likee/<int:id_historia>', views.megusta, name="likee"),
    path('mismemorias/', views.mishistorias, name="mismemorias"),
    path('crearhistorias/', views.crearHist, name="crearhistorias"),
]

apps/usuario/urls.py
from django.urls import path
from . import views

app_name = 'usuario'
urlpatterns = [

    path('login/', views.login_user, name="login"),
    path('registro/', views.registro_user, name="registro"),
    path('logout/', views.logout_user, name="logout"),
]

apps/usuario/models.py
from django.db import models

# Create your models here.

apps/usuario/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from  django.contrib.auth.models import User
from django.contrib import messages
from .form import UserRegistroForm


def login_user(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)

            return HttpResponseRedirect(reverse('historia:index'))

        else:
            messages.error(request, 'El usuario no existe')


    return render(request, 'usuario/login.html',{})

def logout_user(request):

    logout(request)

    return HttpResponseRedirect(reverse('usuario:login'))


def registro_user(request):

    form = UserRegistroForm()

    if request.method == 'POST':
        form = UserRegistroForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']

            user = User.objects.create_user(username,email=email,password=password)
            messages.success(request,'Gracias por registrarse{}'.format(user.username))
            return HttpResponseRedirect(reverse('mascota:index'))
    else:
        form = UserRegistroForm()


    return render(request, 'usuario/registro.html', {'form':form})

templates/usuario/login.html
{% extends 'base/base.html' %}
{% load staticfiles %}

{% block title %}
<title>Login</title>
{% endblock %}

{% block content %}

{% if messages %}

<ul class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class="{{ message.tags }}" {% endif %}> {{ message }}</li>
    {% endfor %}

</ul>
{% endif %}

<form action="" method="post">
    {% csrf_token %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card-group">
                    <div class="card p-4">
                        <div class="card-body">
                            <h1>Identificate</h1>
                            <p class="text-muted">Inicia sesión para continuar</p>
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text">
                                      <i class="icon-user"></i>
                                    </span>
                                </div>
                                <input name="username" class="form-control" type="text" placeholder="Usuario">
                            </div>
                            <div class="input-group mb-4">
                                <div class="input-group-prepend">
                                    <span class="input-group-text">
                                      <i class="icon-lock"></i>
                                    </span>
                                </div>
                                <input name="password" class="form-control" type="password" placeholder="Contraseña">
                            </div>
                            <div class="row">
                                <div class="col-4">
                                    <button class="btn btn-primary px-4" type="submit">Iniciar</button>
                                </div>
                                <div class="col-8 text-right">
                                    <button class="btn btn-link px-0" type="submit">Olvidaste tu contraseña?</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card text-white bg-primary py-5 d-md-down-none">
                        <div class="card-body text-center">
                            <div>
                                <h2 class="text-white">Registrate</h2>
                                <p>Registrate para poder acceder a todo el contenido.</p>
                                <a class="btn btn-primary active mt-3" href="{% url 'usuario:registro' %}">Registrar ahora!</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}

templates/usuario/mimascota.html
{% extends 'base/base.html' %}
{% load staticfiles %}

{% block title %}
<title>Mi Mascotas</title>
{% endblock %}

{% block content %}


{% for mascotas in lis_mas %}

<div class="single-post row">

    <div class="col-lg-3  col-md-3">
        <ul class="popular-post-list">
            <h5>Comportamiento</h5>
            <li>Jugueton %{{ mascotas.id_mascota.jugueton }}
                <div class="skill" data-width="{{ mascotas.id_mascota.jugueton }}"></div>
            </li>
            <li>Educado %{{ mascotas.id_mascota.educado }}
                <div class="skill" data-width="{{ mascotas.id_mascota.educado }}"></div>
            </li>
            <li>Tranquilo %{{ mascotas.id_mascota.tranquilo }}
                <div class="skill" data-width="{{ mascotas.id_mascota.tranquilo }}"></div>
            </li>
            <li>Cariñoso %{{ mascotas.id_mascota.carinioso }}
                <div class="skill" data-width="{{ mascotas.id_mascota.carinioso }}"></div>
            </li>
            <h5>Sociable con</h5>
            <li><p><strong class="fa fa-blind fa-2x"></strong> Adultos : {{ mascotas.id_mascota.adultos }}</p></li>
            <li><p><strong class="fa fa-child fa-2x"></strong> Niños : {{ mascotas.id_mascota.ninios }}</p></li>
            <li><p><strong class="fa fa-paw fa-2x"></strong> Otros animales : {{ mascotas.id_mascota.otros }}</p></li>
            <h5>Salud</h5>
            <li><p>Vacunas : <strong>{{ mascotas.id_mascota.vacuna }}</strong></p></li>
            <li><p>Alergias : <strong>{{ mascotas.id_mascota.alergia }}</strong></p></li>
            <li><p>Enfermedades <strong>{{ mascotas.id_mascota.enfermeda }}</strong></p></li>
            <li><p>Tratamiento : <strong>{{ mascotas.id_mascota.tratamiento }}</strong></p></li>
            <a href="{% url 'historia:addHistorias' %}" class="btn btn-primary">Agregar historia</a>
        </ul>
    </div>
    <div class="col-lg-9 col-md-9">
        <div class="feature-img">
            <img class="img-fluid" src="{{ mascotas.id_mascota.foto }}" alt="">
        </div>
        <a class="posts-title" href="blog-single.html">
            <h3>{{ mascotas.id_mascota.nombre }}</h3></a>
        <p class="excert">
            {{ mascotas.id_mascota.descripcion }}
        </p>
        <div class="meta-details">
            <h5>Características</h5>
            <ul class="tags">
                <li><p>Sexo
                    {% if mascotas.id_mascota.sexo == 'Masculino'%}
                    <strong class="fa fa-mars fa-2x" style="color:blue;"></strong>
                    <strong class="fa fa-venus fa-2x"></strong>
                    {%else%}
                    <strong class="fa fa-mars fa-2x"></strong>
                    <strong class="fa fa-venus fa-2x" style="color:blue;"></strong>
                    {%endif%}
                </p>
                </li>
                <li><p>Tamaño
                    {% if mascotas.id_mascota.tamanio == 'Grande' %}
                    <strong class="fa fa-github"></strong>
                    <strong class="fa fa-github fa-2x"></strong>
                    <strong class="fa fa-github fa-3x" style="color:blue;"></strong>
                    {%endif%}
                    {% if mascotas.id_mascota.tamanio == 'Mediano' %}
                    <strong class="fa fa-github"></strong>
                    <strong class="fa fa-github fa-2x" style="color:blue;"></strong>
                    <strong class="fa fa-github fa-3x"></strong>
                    {%endif%}
                    {% if mascotas.id_mascota.tamanio == 'Pequeño' %}
                    <strong class="fa fa-github" style="color:blue;"></strong>
                    <strong class="fa fa-github fa-2x"></strong>
                    <strong class="fa fa-github fa-3x"></strong>
                    {%endif%}
                </p>
                </li>
                <li>
                    <p>| Raza :
                        <strobg>{{ mascotas.id_mascota.raza }}</strobg>
                        |
                    </p>
                </li>
                <li><p>| años : <strong>{{ mascotas.id_mascota.edad }}</strong> |</p></li>
            </ul>
        </div>
    </div>
</div>

{% endfor %}

<hr>
<div class="col-lg-12 posts-list">
    {% for historia in historia_data %}
    <div class="single-post row">
        <div class="col-lg-3  col-md-3 meta-details">
            <div class="user-details row">
                <p class="user-name col-lg-12 col-md-12 col-6"><a href="#">{{ historia.like }} Lecturas</a> <span
                        class="lnr lnr-user"></span></p>
                <p class="date col-lg-12 col-md-12 col-6"><a href="#">{{ historia.fecha }}</a> <span
                        class="lnr lnr-calendar-full"></span></p>
                <p class="view col-lg-12 col-md-12 col-6"><a href="#">{{ historia.like }} Me gusta</a> <span
                        class="lnr lnr-eye"></span></p>

            </div>
        </div>
        <div class="col-lg-9 col-md-9 ">
            <div class="feature-img">
                <img class="img-fluid" src="{{ historia.imagen.url }}" alt="">
            </div>
            <a class="posts-title" href="blog-single.html"><h3>{{ historia.titulo }}</h3>
            </a>
            <p class="excert">
                {{ historia.historias }}
            </p>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

templates/usuario/registro.html
{% extends 'base/base.html' %}
{% load staticfiles %}

{% block title %}
<title>Registro</title>
{% endblock %}

{% block content %}
<div class="single-post row">
    <div class="col-md-8">
        <div class="card">
            <div class="card-header card-header-primary">
                <h4 class="card-title">Registro de usuarios</h4>
                <p class="card-category">Complete todos los datos por favor</p>
            </div>
            <div class="card-body">
                <form action="" method="POST">
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                {{ field.label_tag}}
                                {{ field }}

                            </div>
                        </div>
                    </div>


                    {% endfor %}
                    <input class="" type="submit" value="Registrar">
                </form>
            </div>
        </div>
    </div>
</div>


{% endblock %}