adopcion/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Home, name='home'),
    path('adoptivo/', include('apps.adoptivo.urls')),
    path('historia/', include('apps.historia.urls',namespace='historia')),
    path('propietario/', include('apps.propietario.urls')),
    path('mascota/', include('apps.mascota.urls',namespace='mascota')),
    path('usuario/', include('apps.usuario.urls',namespace='usuario')),

] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

apps/historia/urls.py
from django.urls import path
from . import views

app_name='historia'
urlpatterns = [
    path('index/', views.index, name="index"),
    path('addHistorias/', views.addHistoria, name="addHistorias"),
    path('likee/<int:id_historia>', views.megusta, name="likee"),
    path('mismemorias/', views.mishistorias, name="mismemorias"),
    path('crearhistorias/', views.crearHist, name="crearhistorias"),
]

apps/mascota/urls.py
from django.urls import path
from . import views

app_name = 'mascota'
urlpatterns = [

    path('index/', views.index, name="index"),
    path('adoptados/', views.adoptadoss, name="adoptados"),
    path('add/', views.add, name="add"),
    path('create/', views.create, name="create"),
    path('edit/<int:id_mascota>', views.edit, name="edit"),
    path('delete/<int:id_mascota>', views.delete, name="delete"),
    path('update/<int:id_mascota>', views.update, name="update"),
    path('show/<int:id_mascota>', views.show, name="show"),
    path('adoptar/<int:id_mascota>', views.adoptarMascota, name="adoptar"),
]

apps/historia/models.py
from django.db import models
from  django.contrib.auth.models import User
from apps.mascota.models import Mascota


class Historia(models.Model):
    id_historia =  models.AutoField(primary_key= True)
    id_mascota = models.ForeignKey(Mascota, on_delete = models.CASCADE)
    id_adoptivo = models.ForeignKey(User, on_delete = models.CASCADE)
    historias = models.TextField()
    fecha = models.DateField()
    like = models.IntegerField(blank=True)
    imagen = models.ImageField(blank=True)
    titulo = models.CharField(max_length=250)

apps/historia/views.py
from django.shortcuts import render,redirect
from .models import Historia
from apps.mascota.models import Mascota
from apps.solicitud.models import Solicitud
from  django.contrib.auth.models import User
from django.core.files.storage import FileSystemStorage

def index(request):

    historias = Historia.objects.all()
    if request.user.is_authenticated:
        user = User.objects.filter(email__exact='request.user.email')
        hist = Historia.objects.filter(id_adoptivo__exact=request.user.id)

    mycontext = {
        'historia_data':historias,
        'list_historia':hist
    }
    print(historias)
    return render(request, 'base/base.html', mycontext)


def megusta(request, id_historia):
    histori = Historia.objects.get(pk=id_historia)
    like = histori.like
    likes = like + 1

    histori.like = likes

    histori.save()
    return redirect('historia:index')

def addHistoria(request):

    mycontext={'mas':'hola mundo'}
    return render(request,'historia/crearHistoria.html')


def crearHist(request):
    if request.user.is_authenticated:
        solicitud = Solicitud.objects.filter(id_user__exact=request.user.id)
        for da in solicitud:
            print('valor : id_buscado')
            print(da.id_mascota.id_mascota)
            idd = da.id_mascota.id_mascota

        id_mascota = Mascota.objects.get(pk=idd)
        id_adoptivo = request.user
        titulo = request.POST['titulo']
        fecha = request.POST['fecha']
        historias = request.POST['historias']
        like = 0
        myfile = request.FILES['imagen']
        fs = FileSystemStorage()
        filename = fs.save(myfile.name, myfile)
        uploaded_file_url = fs.url(filename)


        historia = Historia(
           id_mascota = id_mascota,
            id_adoptivo = id_adoptivo,
            historias = historias,
            fecha = fecha,
            like = like,
            titulo = titulo,
            imagen = uploaded_file_url

        )
        historia.save()
        return redirect('historia:addHistorias')


def mishistorias(request):

    if request.user.is_authenticated:
        hist = Historia.objects.filter(id_adoptivo__exact=request.user.id)
        mascotas = Solicitud.objects.filter(id_user__exact=request.user.id)

        mycontext = {
            'historia_data':hist,
            'list_historia':hist,
            'lis_mas':mascotas
        }

        return render(request, 'usuario/mimascota.html', mycontext)

templates/historia/crearHistoria.html
{% extends 'base/base.html' %}
{% load staticfiles %}

{% block title %}
<title>Agregar Mascotas</title>
{% endblock %}

{% block content %}

<div class="single-post row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header card-header-primary">
                <h4 class="card-title">Mascota en adopción</h4>
                <p class="card-category">Complete todos los datos por favor</p>
            </div>
            <div class="card-body">
                <form action="{% url 'historia:crearhistorias' %}" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <h4 class="card-title">Características principales</h4>
                    <div class="row">
                        <div class="col-md-9">
                            <div class="form-group">
                                <label class="bmd-label-floating">Título</label>
                                <input class="form-control" type="text" name="titulo">
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <label class="bmd-label-floating">Fecha</label>
                                <input class="form-control" type="date" name="fecha">
                            </div>
                        </div>

                    </div>
                    <div class="row">
                         <div class="col-md-12">
                            <div class="form-group">
                                <label class="bmd-label-floating">Subir imagen </label>
                                <input class="form-control" type="file" name="imagen" >
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>Mis memorias</label>
                                <div class="form-group">
                                    <label class="bmd-label-floating"> Escribe tu historia.</label>
                                    <textarea name="historias" class="form-control" rows="5"></textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary pull-right">Agregar</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/historia/mimascota.html
{% extends 'base/base.html' %}
{% load staticfiles %}

{% block title %}
<title>Mi Mascotas</title>
{% endblock %}

{% block content %}

<div class="single-post row">

    <div class="col-lg-3  col-md-3">
        <ul class="popular-post-list">
            <h5>Comportamiento</h5>
            <li>Jugueton %{{ mascotas.jugueton }}
                <div class="skill" data-width="{{ mascotas.jugueton }}"></div>
            </li>
            <li>Educado %{{ mascotas.educado }}
                <div class="skill" data-width="{{ mascotas.educado }}"></div>
            </li>
            <li>Tranquilo %{{ mascotas.tranquilo }}
                <div class="skill" data-width="{{ mascotas.tranquilo }}"></div>
            </li>
            <li>Cariñoso %{{ mascotas.carinioso }}
                <div class="skill" data-width="{{ mascotas.carinioso }}"></div>
            </li>
            <h5>Sociable con</h5>
            <li><p><strong class="fa fa-blind fa-2x"></strong> Adultos : {{ mascotas.adultos }}</p></li>
            <li><p><strong class="fa fa-child fa-2x"></strong> Niños : {{ mascotas.ninios }}</p></li>
            <li><p><strong class="fa fa-paw fa-2x"></strong> Otros animales : {{ mascotas.otros }}</p></li>
            <h5>Salud</h5>
            <li><p>Vacunas : <strong>{{ mascotas.vacuna }}</strong></p></li>
            <li><p>Alergias : <strong>{{ mascotas.alergia }}</strong></p></li>
            <li><p>Enfermedades <strong>{{ mascotas.enfermeda }}</strong></p></li>
            <li><p>Tratamiento : <strong>{{ mascotas.tratamiento }}</strong></p></li>
            <a href="{% url 'mascota:adoptar' id_mascota=mascotas.id_mascota %}" class="btn btn-primary">Adoptar</a>

        </ul>
        <a href="{% url 'mascota:adoptar' id_mascota=mascotas.id_mascota %}" class="btn btn-primary">Agregar historia</a>
    </div>
    <div class="col-lg-9 col-md-9">
        <div class="feature-img">
            <img class="img-fluid" src="{{ mascotas.foto.url }}" alt="">
        </div>
        <a class="posts-title" href="blog-single.html">
            <h3>{{ mascotas.nombre }}</h3></a>
        <p class="excert">
            {{ mascotas.descripcion }}
        </p>
        <div class="meta-details">
            <h5>Características</h5>
            <ul class="tags">
                <li><p>Sexo
                    {% if mascotas.sexo == 'Masculino'%}
                    <strong class="fa fa-mars fa-2x" style="color:blue;"></strong>
                    <strong class="fa fa-venus fa-2x"></strong>
                    {%else%}
                    <strong class="fa fa-mars fa-2x"></strong>
                    <strong class="fa fa-venus fa-2x" style="color:blue;"></strong>
                    {%endif%}
                </p>
                </li>
                <li><p>Tamaño
                    {% if mascotas.tamanio == 'Grande' %}
                    <strong class="fa fa-github"></strong>
                    <strong class="fa fa-github fa-2x"></strong>
                    <strong class="fa fa-github fa-3x" style="color:blue;"></strong>
                    {%endif%}
                    {% if mascotas.tamanio == 'Mediano' %}
                    <strong class="fa fa-github"></strong>
                    <strong class="fa fa-github fa-2x" style="color:blue;"></strong>
                    <strong class="fa fa-github fa-3x"></strong>
                    {%endif%}
                    {% if mascotas.tamanio == 'Pequeño' %}
                    <strong class="fa fa-github" style="color:blue;"></strong>
                    <strong class="fa fa-github fa-2x"></strong>
                    <strong class="fa fa-github fa-3x"></strong>
                    {%endif%}
                </p>
                </li>
                <li>
                    <p>| Raza :
                        <strobg>{{ mascotas.raza }}</strobg>
                        |
                    </p>
                </li>
                <li><p>| años : <strong>{{ mascotas.edad }}</strong> |</p></li>
            </ul>
        </div>
        <div>
            <h5>Mi historia</h5>
            <p class="excert">{{ mascotas.mihistoria }}</p>
        </div>
    </div>
</div>
<hr>
<div class="col-lg-8 posts-list">
    {% for historia in historia_data %}
    <div class="single-post row">
        <div class="col-lg-3  col-md-3 meta-details">
            <div class="user-details row">
                <p class="user-name col-lg-12 col-md-12 col-6"><a href="#">{{ historia.like }} Lecturas</a> <span
                        class="lnr lnr-user"></span></p>
                <p class="date col-lg-12 col-md-12 col-6"><a href="#">{{ historia.fecha }}</a> <span
                        class="lnr lnr-calendar-full"></span></p>
                <p class="view col-lg-12 col-md-12 col-6"><a href="#">{{ historia.like }} Me gusta</a> <span
                        class="lnr lnr-eye"></span></p>

            </div>
        </div>
        <div class="col-lg-9 col-md-9 ">
            <div class="feature-img">
                <img class="img-fluid" src="{{ historia.imagen}}" alt="">
            </div>
            <a class="posts-title" href="blog-single.html"><h3>{{ historia.titulo }}</h3>
            </a>
            <p class="excert">
                {{ historia.historias }}
            </p>
            <a href="{% url 'historia:likee' id_historia=historia.id_historia %}" class="primary-btn">Me gusta</a>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}