adopcion/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Home, name='home'),
    path('adoptivo/', include('apps.adoptivo.urls')),
    path('historia/', include('apps.historia.urls',namespace='historia')),
    path('propietario/', include('apps.propietario.urls')),
    path('mascota/', include('apps.mascota.urls',namespace='mascota')),
    path('usuario/', include('apps.usuario.urls',namespace='usuario')),

] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

apps/historia/urls.py
from django.urls import path
from . import views

app_name='historia'
urlpatterns = [
    path('index/', views.index, name="index"),
    path('addHistorias/', views.addHistoria, name="addHistorias"),
    path('likee/<int:id_historia>', views.megusta, name="likee"),
    path('mismemorias/', views.mishistorias, name="mismemorias"),
    path('crearhistorias/', views.crearHist, name="crearhistorias"),
]

apps/mascota/urls.py
from django.urls import path
from . import views

app_name = 'mascota'
urlpatterns = [

    path('index/', views.index, name="index"),
    path('adoptados/', views.adoptadoss, name="adoptados"),
    path('add/', views.add, name="add"),
    path('create/', views.create, name="create"),
    path('edit/<int:id_mascota>', views.edit, name="edit"),
    path('delete/<int:id_mascota>', views.delete, name="delete"),
    path('update/<int:id_mascota>', views.update, name="update"),
    path('show/<int:id_mascota>', views.show, name="show"),
    path('adoptar/<int:id_mascota>', views.adoptarMascota, name="adoptar"),
]

apps/usuario/urls.py
from django.urls import path
from . import views

app_name = 'usuario'
urlpatterns = [

    path('login/', views.login_user, name="login"),
    path('registro/', views.registro_user, name="registro"),
    path('logout/', views.logout_user, name="logout"),
]

templates/base/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="zxx" class="no-js">
<head>
    <!-- Mobile Specific Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicon-->
    <link rel="shortcut icon" href="img/fav.png">
    <!-- Author Meta -->
    <meta name="author" content="colorlib">
    <!-- Meta Description -->
    <meta name="description" content="">
    <!-- Meta Keyword -->
    <meta name="keywords" content="">
    <!-- meta character set -->
    <meta charset="UTF-8">
    <!-- Site Title -->
    {% block title %}
    <title>Mascotas</title>
    {% endblock %}

    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
    <!--
    CSS
    ============================================= -->
    <link rel="stylesheet" href="{%static 'css/linearicons.css'%}">
    <link rel="stylesheet" href="{%static 'css/font-awesome.min.css'%}">
    <link rel="stylesheet" href="{%static 'css/bootstrap.css'%}">
    <link rel="stylesheet" href="{%static 'css/magnific-popup.css'%}">
    <link rel="stylesheet" href="{%static 'css/nice-select.css'%}">
    <link rel="stylesheet" href="{%static 'css/animate.min.css'%}">
    <link rel="stylesheet" href="{%static 'css/owl.carousel.css'%}">
    <link rel="stylesheet" href="{%static 'css/jquery-ui.css'%}">
    <link rel="stylesheet" href="{%static 'css/main.css'%}">
</head>
<body>
{% block navbar %}
<header id="header" style="background-color: #fff;">
    <div class="container main-menu">
        <div class="row align-items-center justify-content-between d-flex">
            <div id="logo">
                <a href="index.html"><img style="width:100px;" src="{%static 'img/descarga.png'%}" alt="" title=""/></a>
            </div>
            <nav id="nav-menu-container">
                <ul class="nav-menu">

                    {% if request.user.is_authenticated %}
                    <li><a href="{% url 'historia:index' %}">Historias</a></li>
                    <li><a href="{% url 'mascota:adoptados' %}">Adopciones</a></li>
                    <li><a href="{% url 'mascota:index' %}">Adoptame</a></li>
                    {% endif %}
                    {% if request.user.is_authenticated %}
                    <li><a href="{% url 'usuario:logout' %}">Salir</a></li>
                    {% else %}
                    <li><a href="{% url 'usuario:login' %}">Login</a></li>
                    {% endif %}

                </ul>
            </nav><!-- #nav-menu-container -->
        </div>
    </div>
</header><!-- #header -->
{% endblock %}

<!-- Start post-content Area -->
<section class="post-content-area pt-90 pb-90">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 posts-list">
                {% block content %}

                {% for historia in historia_data %}
                <div class="single-post row">
                    <div class="col-lg-3  col-md-3 meta-details">
                        <div class="user-details row">
                            <p class="user-name col-lg-12 col-md-12 col-6"><a href="#">{{ historia.like }} Lecturas</a> <span
                                    class="lnr lnr-user"></span></p>
                            <p class="date col-lg-12 col-md-12 col-6"><a href="#">{{ historia.fecha }}</a> <span
                                    class="lnr lnr-calendar-full"></span></p>
                            <p class="view col-lg-12 col-md-12 col-6"><a href="#">{{ historia.like }} Me gusta</a> <span
                                    class="lnr lnr-eye"></span></p>

                        </div>
                    </div>
                    <div class="col-lg-9 col-md-9 ">
                        <div class="feature-img">
                            <img class="img-fluid" src="{{ historia.imagen }}" alt="">
                        </div>
                        <a class="posts-title" href="blog-single.html"><h3>{{ historia.titulo }}</h3>
                        </a>
                        <div class="meta-details">
                            <ul class="tags">
                                <li><p>Adoptado por : </p></li>
                                <li><p>{{ historia.id_adoptivo.username }} </p></li>

                            </ul>
                        </div>
                        <p class="excert">
                            {{ historia.historias }}
                        </p>
                        <a href="{% url 'historia:likee' id_historia=historia.id_historia %}" class="primary-btn">Me gusta</a>
                    </div>
                </div>
                {% endfor %}
                {% endblock %}
            </div>

            <div class="col-lg-4 sidebar-widgets">
                {% block perfil %}
                <div class="widget-wrap">
                    <div class="single-sidebar-widget popular-post-widget">
                        <h4 class="popular-title">Mi perfil</h4>
                    </div>
                    <div class="single-sidebar-widget user-info-widget">
                        <img src="{%static 'img/blog/user-info.png'%}" alt="">
                        {% if request.user.is_authenticated %}
                        <a href="#"><h4>{{request.user}}</h4></a>
                        <a href="#"><h4>{{request.user.email}}</h4></a>
                        <li><p><a href="{% url 'historia:mismemorias' %}">Mis memorias</a></p></li>
                        <li><p><a href="{% url 'mascota:add' %}" class="">Agregar mascota</a></p></li>
                        {% else %}
                        <a href="#"><h4>Visitante</h4></a>
                        {% endif %}
                        <p>
                            Todos los amigos peluditos necesitan un hogar
                        </p>
                    </div>
                    <div class="single-sidebar-widget popular-post-widget">
                        <h4 class="popular-title">Historias</h4>
                        <div class="popular-post-list">

                            {% for list in list_historia %}
                            <div class="single-post-list d-flex flex-row align-items-center">
                                <div class="thumb">
                                    <img class="img-fluid" src="img/blog/pp1.jpg" alt="">
                                </div>
                                <div class="details">
                                    <a href="blog-single.html"><h6>{{ list.titulo }}</h6></a>
                                    <p>{{ list.fecha }}</p>
                                </div>
                            </div>
                            {% endfor %}


                        </div>
                    </div>
                </div>
                {% endblock %}
            </div>
        </div>
    </div>
</section>
<!-- End post-content Area -->

{% block footer %}
<!-- start footer Area -->
<footer class="footer-area section-gap">
    <div class="container">
        <div class="row">
            <div class="col-lg-5 col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h4>About Me</h4>
                    <p>
                        We have tested a number of registry fix and clean utilities and present our top 3 list on our
                        site for your convenience.
                    </p>
                    <p class="footer-text">
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        Copyright &copy;<script>document.write(new Date().getFullYear());</script>
                        All rights reserved | This template is made with <i class="fa fa-heart-o"
                                                                            aria-hidden="true"></i> by <a
                            href="https://colorlib.com" target="_blank">Colorlib</a>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
                </div>
            </div>
            <div class="col-lg-5 col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h4>Newsletter</h4>
                    <p>Stay updated with our latest trends</p>
                    <div class="" id="mc_embed_signup">
                        <form target="_blank"
                              action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
                              method="get">
                            <div class="input-group">
                                <input type="text" class="form-control" name="EMAIL" placeholder="Enter Email Address"
                                       onfocus="this.placeholder = ''"
                                       onblur="this.placeholder = 'Enter Email Address '" required="" type="email">
                                <div class="input-group-btn">
                                    <button class="btn btn-default" type="submit">
                                        <span class="lnr lnr-arrow-right"></span>
                                    </button>
                                </div>
                                <div class="info"></div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-2 col-md-6 col-sm-6 social-widget">
                <div class="single-footer-widget">
                    <h4>Follow Me</h4>
                    <p>Let us be social</p>
                    <div class="footer-social d-flex align-items-center">
                        <a href="#"><i class="fa fa-facebook"></i></a>
                        <a href="#"><i class="fa fa-twitter"></i></a>
                        <a href="#"><i class="fa fa-dribbble"></i></a>
                        <a href="#"><i class="fa fa-behance"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- End footer Area -->
{% endblock %}

<script src="{%static 'js/vendor/jquery-2.2.4.min.js'%}"></script>
<script src="{%static 'js/popper.min.js'%}"></script>
<script src="{%static 'js/vendor/bootstrap.min.js'%}"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
<script src="{%static 'js/easing.min.js'%}"></script>
<script src="{%static 'js/hoverIntent.js'%}"></script>
<script src="{%static 'js/superfish.min.js'%}"></script>
<script src="{%static 'js/jquery.ajaxchimp.min.js'%}"></script>
<script src="{%static 'js/jquery.magnific-popup.min.js'%}"></script>
<script src="{%static 'js/jquery.tabs.min.js'%}"></script>
<script src="{%static 'js/jquery.nice-select.min.js'%}"></script>
<script src="{%static 'js/isotope.pkgd.min.js'%}"></script>
<script src="{%static 'js/waypoints.min.js'%}"></script>
<script src="{%static 'js/jquery.counterup.min.js'%}"></script>
<script src="{%static 'js/simple-skillbar.js'%}"></script>
<script src="{%static 'js/owl.carousel.min.js'%}"></script>
<script src="{%static 'js/mail-script.js'%}"></script>
<script src="{%static 'js/main.js'%}"></script>


</body>
</html>