adopcion/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Home, name='home'),
    path('adoptivo/', include('apps.adoptivo.urls')),
    path('historia/', include('apps.historia.urls',namespace='historia')),
    path('propietario/', include('apps.propietario.urls')),
    path('mascota/', include('apps.mascota.urls',namespace='mascota')),
    path('usuario/', include('apps.usuario.urls',namespace='usuario')),

] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

apps/adoptivo/urls.py
from django.urls import path
from . import views

app_name='adoptivo'
urlpatterns = [
    path('index/', views.index, name="index"),
    path('add/', views.add, name="add"),
    path('create/', views.create, name="create"),
    path('edit/<int:id_adoptivo>', views.edit, name="edit"),
    path('delete/<int:id_adoptivo>', views.delete, name="delete"),
    path('update/<int:id_adoptivo>', views.update, name="update"),
    path('show/<int:id_adoptivo>', views.show, name="show"),

]

apps/mascota/urls.py
from django.urls import path
from . import views

app_name = 'mascota'
urlpatterns = [

    path('index/', views.index, name="index"),
    path('adoptados/', views.adoptadoss, name="adoptados"),
    path('add/', views.add, name="add"),
    path('create/', views.create, name="create"),
    path('edit/<int:id_mascota>', views.edit, name="edit"),
    path('delete/<int:id_mascota>', views.delete, name="delete"),
    path('update/<int:id_mascota>', views.update, name="update"),
    path('show/<int:id_mascota>', views.show, name="show"),
    path('adoptar/<int:id_mascota>', views.adoptarMascota, name="adoptar"),
]

apps/adoptivo/models.py
from django.db import models

class Adoptivo(models.Model):
    id_adoptivo = models.AutoField(primary_key= True)
    nombres = models.CharField(max_length=250)
    apellidos = models.CharField(max_length=250)
    ci_adop = models.CharField(max_length=11)
    direccion = models.CharField(max_length=250)
    email = models.EmailField()
    telefono = models.CharField(max_length=20)
    edad = models.IntegerField()

apps/adoptivo/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Adoptivo

def index(request):
    adoptivo = Adoptivo.objects.all();
    mycontext = {
        'adoptivo_data':adoptivo
    }
    return render(request, 'adoptivo/index.html', mycontext)

def add(request):
    pass

def create(request):
    pass

def delete(request, id_adoptivo):
    pass


def edit(request, id_adoptivo):
    pass

def update(request,id_adoptivo):
    pass

def show(request, id_adoptivo):
    pass

templates/adoptivo/addMascota.html
{% extends 'base/base.html' %}
{% load staticfiles %}

{% block title %}
<title>Agregar Mascotas</title>
{% endblock %}

{% block content %}

<div class="single-post row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header card-header-primary">
                <h4 class="card-title">Mascota en adopción</h4>
                <p class="card-category">Complete todos los datos por favor</p>
            </div>
            <div class="card-body">
                <form action="{% url 'mascota:create' %}" method="POST">
                    {%  csrf_token %}
                    <h4 class="card-title">Características principales</h4>
                    <div class="row">
                        <div class="col-md-5">
                            <div class="form-group">
                                <label class="bmd-label-floating">Ci propietario</label>
                                <input name="cip" type="text" class="form-control">
                            </div>
                        </div>
                        <div class="col-md-5">
                            <div class="form-group">
                                <label class="bmd-label-floating">Nombre de la mascota</label>
                                <input name="nombre" type="text" class="form-control">
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <label class="bmd-label-floating">Edad</label>
                                <input class="form-control" type="number" name="edad" min="0" max="10">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">
                            <div class="form-group">
                                <label class="bmd-label-floating">Elija la raza</label>
                                <select class="form-control"  name="raza">
                                    <option value="Pitbull">Pitbull</option>
                                    <option value="Salchicha">Salchicha</option>
                                    <option value="Labrador">Labrador</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-9">
                            <div class="form-group">
                                <label class="bmd-label-floating">Descripción</label>
                                <textarea name="descripcion" type="text" class="form-control"></textarea>
                            </div>
                        </div>
                    </div>
                    <h4 class="card-title">Descripción física</h4>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="bmd-label-floating">Elija el tamaño</label>
                                <select class="form-control"  name="tamanio">
                                    <option value="Grande">Grande</option>
                                    <option value="Mediano">Mediano</option>
                                    <option value="Pequeño">Pequeño</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="bmd-label-floating">Elija el Género</label>
                                <select class="form-control"  name="sexo">
                                    <option value="Masculino">Masculino</option>
                                    <option value="Femenino">Femenino</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="bmd-label-floating">Enfermedades crónicas</label>
                                <select class="form-control"  name="enfermedad">
                                    <option value="Si">Si</option>
                                    <option value="No">No</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="bmd-label-floating">Tratamientos</label>
                                <select class="form-control"  name="tratamiento">
                                    <option value="Si">Si</option>
                                    <option value="No">No</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="bmd-label-floating">Alergias</label>
                                <select class="form-control"  name="alergia">
                                    <option value="Si">Si</option>
                                    <option value="No">No</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="bmd-label-floating">Vacunas</label>
                                <select class="form-control"  name="vacuna">
                                    <option value="Si">Si</option>
                                    <option value="No">No</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <h4 class="card-title">Comportamiento  % </h4>
                    <div class="row">
                        <div class="col-md-3">
                            <div class="form-group">
                                <label class="bmd-label-floating">Cariñoso</label>
                                <input class="form-control" type="number" name="carinioso" min="0" max="100">
                            </div>
                        </div>
                         <div class="col-md-3">
                            <div class="form-group">
                                <label class="bmd-label-floating">Juguetón</label>
                                <input class="form-control" type="number" name="jugueton" min="0" max="100">
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <label class="bmd-label-floating">Tranquilo</label>
                                <input class="form-control" type="number" name="tranquilo" min="0" max="100">
                            </div>
                        </div>
                         <div class="col-md-3">
                            <div class="form-group">
                                <label class="bmd-label-floating">Educado</label>
                                <input class="form-control" type="number" name="educado" min="0" max="100">
                            </div>
                        </div>
                    </div>
                     <h4 class="card-title">Sociable con</h4>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="bmd-label-floating">Adultos</label>
                                <select class="form-control"  name="adulto">
                                    <option value="Si">Si</option>
                                    <option value="No">No</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="bmd-label-floating">Niños</label>
                                <select class="form-control"  name="ninio">
                                    <option value="Si">Si</option>
                                    <option value="No">No</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="bmd-label-floating">Otros animales</label>
                                <select class="form-control"  name="otro">
                                    <option value="Si">Si</option>
                                    <option value="No">No</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>Mi historia</label>
                                <div class="form-group">
                                    <label class="bmd-label-floating"> Escribe un fragmento de la historia de tu mascota, esto ayudará a que empatizar con ella.</label>
                                    <textarea name="historia" class="form-control" rows="5"></textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary pull-right">Agregar</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/adoptivo/adoptar.html
{% extends 'base/base.html' %}
{% load staticfiles %}

{% block title %}
<title>Mi Mascotas</title>
{% endblock %}

{% block content %}

<div class="single-post row">

    <div class="col-lg-3  col-md-3">
        <ul class="popular-post-list">
            <h5>Comportamiento</h5>
            <li>Jugueton %{{ mascotas.jugueton }}
                <div class="skill" data-width="{{ mascotas.jugueton }}"></div>
            </li>
            <li>Educado %{{ mascotas.educado }}
                <div class="skill" data-width="{{ mascotas.educado }}"></div>
            </li>
            <li>Tranquilo %{{ mascotas.tranquilo }}
                <div class="skill" data-width="{{ mascotas.tranquilo }}"></div>
            </li>
            <li>Cariñoso %{{ mascotas.carinioso }}
                <div class="skill" data-width="{{ mascotas.carinioso }}"></div>
            </li>
            <h5>Sociable con</h5>
            <li><p><strong class="fa fa-blind fa-2x"></strong> Adultos : {{ mascotas.adultos }}</p></li>
            <li><p><strong class="fa fa-child fa-2x"></strong> Niños : {{ mascotas.ninios }}</p></li>
            <li><p><strong class="fa fa-paw fa-2x"></strong> Otros animales : {{ mascotas.otros }}</p></li>
            <h5>Salud</h5>
            <li><p>Vacunas : <strong>{{ mascotas.vacuna }}</strong></p></li>
            <li><p>Alergias : <strong>{{ mascotas.alergia }}</strong></p></li>
            <li><p>Enfermedades <strong>{{ mascotas.enfermeda }}</strong></p></li>
            <li><p>Tratamiento : <strong>{{ mascotas.tratamiento }}</strong></p></li>
            <a href="{% url 'mascota:adoptar' id_mascota=mascotas.id_mascota %}" class="btn btn-primary">Adoptar</a>
        </ul>
    </div>
    <div class="col-lg-9 col-md-9">
        <div class="feature-img">
            <img class="img-fluid" src="{%static 'img/blog/feature-img1.jpg'%}" alt="">
        </div>
        <a class="posts-title" href="blog-single.html">
            <h3>{{ mascotas.nombre }}</h3></a>
        <p class="excert">
            {{ mascotas.descripcion }}
        </p>
        <div class="meta-details">
            <h5>Características</h5>
            <ul class="tags">
                <li><p>Sexo
                    {% if mascotas.sexo == 'Masculino'%}
                    <strong class="fa fa-mars fa-2x" style="color:blue;"></strong>
                    <strong class="fa fa-venus fa-2x"></strong>
                    {%else%}
                    <strong class="fa fa-mars fa-2x"></strong>
                    <strong class="fa fa-venus fa-2x" style="color:blue;"></strong>
                    {%endif%}
                </p>
                </li>
                <li><p>Tamaño
                    {% if mascotas.tamanio == 'Grande' %}
                    <strong class="fa fa-github"></strong>
                    <strong class="fa fa-github fa-2x"></strong>
                    <strong class="fa fa-github fa-3x" style="color:blue;"></strong>
                    {%endif%}
                    {% if mascotas.tamanio == 'Mediano' %}
                    <strong class="fa fa-github"></strong>
                    <strong class="fa fa-github fa-2x" style="color:blue;"></strong>
                    <strong class="fa fa-github fa-3x"></strong>
                    {%endif%}
                    {% if mascotas.tamanio == 'Pequeño' %}
                    <strong class="fa fa-github" style="color:blue;"></strong>
                    <strong class="fa fa-github fa-2x"></strong>
                    <strong class="fa fa-github fa-3x"></strong>
                    {%endif%}
                </p>
                </li>
                <li>
                    <p>| Raza :
                        <strobg>{{ mascotas.raza }}</strobg>
                        |
                    </p>
                </li>
                <li><p>| años : <strong>{{ mascotas.edad }}</strong> |</p></li>
            </ul>
        </div>
        <div>
            <h5>Mi historia</h5>
            <p class="excert">{{ mascotas.mihistoria }}</p>
        </div>
    </div>
</div>
<hr>

{% endblock %}

templates/adoptivo/editMascota.html
{% extends 'base/base.html' %}
{% load staticfiles %}

{% block title %}
<title>Agregar Mascotas</title>
{% endblock %}

{% block content %}

<div class="single-post row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header card-header-primary">
                <h4 class="card-title">Mascota en adopción</h4>
                <p class="card-category">Complete todos los datos por favor</p>
            </div>
            <div class="card-body">
                <form action="{% url 'mascota:update' id_mascota=mascotas_data.id_mascota %}" method="POST">
                    {%  csrf_token %}
                    <h4 class="card-title">Características principales</h4>
                    <div class="row">
                        <div class="col-md-5">
                            <div class="form-group">
                                <label class="bmd-label-floating">Ci propietario</label>
                                <input name="cip" type="text" class="form-control" value="{{mascotas_data.ci_pro}}">
                            </div>
                        </div>
                        <div class="col-md-5">
                            <div class="form-group">
                                <label class="bmd-label-floating">Nombre de la mascota</label>
                                <input name="nombre" type="text" class="form-control" value="{{mascotas_data.nombre}}">
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <label class="bmd-label-floating">Edad</label>
                                <input class="form-control" type="number" name="edad" min="0" max="10" value="{{mascotas_data.edad}}">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">
                            <div class="form-group">
                                <label class="bmd-label-floating">Elija la raza</label>
                                <select class="form-control"  name="raza">
                                    <option value="Pitbull">Pitbull</option>
                                    <option value="Salchicha">Salchicha</option>
                                    <option value="Labrador">Labrador</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-9">
                            <div class="form-group">
                                <label class="bmd-label-floating">Descripción</label>
                                <textarea name="descripcion" type="text" class="form-control">{{mascotas_data.descripcion}}</textarea>
                            </div>
                        </div>
                    </div>
                    <h4 class="card-title">Descripción física</h4>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="bmd-label-floating">Elija el tamaño</label>
                                <select class="form-control"  name="tamanio">
                                    <option value="Grande">Grande</option>
                                    <option value="Mediano">Mediano</option>
                                    <option value="Pequeño">Pequeño</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="bmd-label-floating">Elija el Género</label>
                                <select class="form-control"  name="sexo">
                                    <option value="Masculino">Masculino</option>
                                    <option value="Femenino">Femenino</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="bmd-label-floating">Enfermedades crónicas</label>
                                <select class="form-control"  name="enfermedad">
                                    <option value="Si">Si</option>
                                    <option value="No">No</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="bmd-label-floating">Tratamientos</label>
                                <select class="form-control"  name="tratamiento">
                                    <option value="Si">Si</option>
                                    <option value="No">No</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="bmd-label-floating">Alergias</label>
                                <select class="form-control"  name="alergia">
                                    <option value="Si">Si</option>
                                    <option value="No">No</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="bmd-label-floating">Vacunas</label>
                                <select class="form-control"  name="vacuna">
                                    <option value="Si">Si</option>
                                    <option value="No">No</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <h4 class="card-title">Comportamiento  % </h4>
                    <div class="row">
                        <div class="col-md-3">
                            <div class="form-group">
                                <label class="bmd-label-floating">Cariñoso</label>
                                <input class="form-control" type="number" name="carinioso" min="0" max="100" value="{{mascotas_data.carinioso}}">
                            </div>
                        </div>
                         <div class="col-md-3">
                            <div class="form-group">
                                <label class="bmd-label-floating">Juguetón</label>
                                <input class="form-control" type="number" name="jugueton" min="0" max="100" value="{{mascotas_data.jugueton}}">
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <label class="bmd-label-floating">Tranquilo</label>
                                <input class="form-control" type="number" name="tranquilo" min="0" max="100" value="{{mascotas_data.tranquilo}}">
                            </div>
                        </div>
                         <div class="col-md-3">
                            <div class="form-group">
                                <label class="bmd-label-floating">Educado</label>
                                <input class="form-control" type="number" name="educado" min="0" max="100" value="{{mascotas_data.educado}}">
                            </div>
                        </div>
                    </div>
                     <h4 class="card-title">Sociable con</h4>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="bmd-label-floating">Adultos</label>
                                <select class="form-control"  name="adulto">
                                    <option value="Si">Si</option>
                                    <option value="No">No</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="bmd-label-floating">Niños</label>
                                <select class="form-control"  name="ninio">
                                    <option value="Si">Si</option>
                                    <option value="No">No</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="bmd-label-floating">Otros animales</label>
                                <select class="form-control"  name="otro">
                                    <option value="Si">Si</option>
                                    <option value="No">No</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>Mi historia</label>
                                <div class="form-group">
                                    <label class="bmd-label-floating"> Escribe un fragmento de la historia de tu mascota, esto ayudará a que empatizar con ella.</label>
                                    <textarea name="historia" class="form-control" rows="5">{{mascotas_data.mihistoria}}</textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary pull-right">Editar</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/adoptivo/index.html
{% extends 'base/base.html' %}
{% load staticfiles %}

{% block title %}
<title>Mi perfil</title>
{% endblock %}

{% block content %}


<div class="single-post row">

    <div class="col-lg-3  col-md-3">
        <ul class="popular-post-list">
            <h5>Comportamiento</h5>
            <li>Jugueton %{{ adoptivo_data.nombres }}
                <div class="skill" data-width="{{ mascotas.jugueton }}"></div>
            </li>
            <li>Educado %{{ adoptivo_data.apellidos }}
                <div class="skill" data-width="{{ mascotas.educado }}"></div>
            </li>
            <li>Tranquilo %{{ adoptivo_data.ci_adop }}
                <div class="skill" data-width="{{ mascotas.tranquilo }}"></div>
            </li>
            <h5>Sociable con</h5>
            <li><p><strong class="fa fa-blind fa-2x"></strong> Adultos : {{ adoptivo_data.direccion }}</p></li>
            <li><p><strong class="fa fa-child fa-2x"></strong> Niños : {{ adoptivo_data.email }}</p></li>
            <li><p><strong class="fa fa-paw fa-2x"></strong> Otros animales : {{ adoptivo_data.telefono }}</p></li>
            <a href="{% url 'mascota:show' id_mascota=mascotas.id_mascota %}" class="btn btn-primary">Adopta un amigo</a>
            <a href="{% url 'mascota:delete' id_mascota=mascotas.id_mascota %}" class="btn btn-primary">Eliminar</a>
            <a href="{% url 'mascota:edit' id_mascota=mascotas.id_mascota %}" class="btn btn-primary">Editar</a>
        </ul>
    </div>
    <div class="col-lg-9 col-md-9">
        <div class="feature-img">
            <img class="img-fluid" src="{%static 'img/blog/feature-img1.jpg'%}" alt="">
        </div>
        <a class="posts-title" href="blog-single.html"><h3>{{ adoptivo_data.edad }}</h3></a>
        <p class="excert">
            {{ mascotas.descripcion }}
        </p>
        <div class="meta-details">
            <h5>Características</h5>
            <ul class="tags">
                <li><p>Sexo
                    {% if mascotas.sexo == 'Masculino'%}
                        <strong class="fa fa-mars fa-2x" style="color:blue;"></strong>
                        <strong class="fa fa-venus fa-2x"></strong>
                    {%else%}
                        <strong class="fa fa-mars fa-2x"></strong>
                        <strong class="fa fa-venus fa-2x" style="color:blue;"></strong>
                    {%endif%}
                    </p>
                </li>
                <li><p>Tamaño
                    {% if mascotas.tamanio == 'Grande' %}
                        <strong class="fa fa-github"></strong>
                        <strong class="fa fa-github fa-2x"></strong>
                        <strong class="fa fa-github fa-3x" style="color:blue;"></strong>
                    {%endif%}
                    {% if mascotas.tamanio == 'Mediano' %}
                        <strong class="fa fa-github"></strong>
                        <strong class="fa fa-github fa-2x" style="color:blue;"></strong>
                        <strong class="fa fa-github fa-3x"></strong>
                    {%endif%}
                    {% if mascotas.tamanio == 'Pequeño' %}
                        <strong class="fa fa-github" style="color:blue;"></strong>
                        <strong class="fa fa-github fa-2x"></strong>
                        <strong class="fa fa-github fa-3x"></strong>
                    {%endif%}
                    </p>
                </li>
                <li><p>|       Raza :   <strobg>{{ mascotas.raza }}</strobg>  |</p></li>
                <li><p>|       años :   <strong>{{ mascotas.edad }}</strong>  |</p></li>
                <li><p>|       vacunas :   <strong>{{ mascotas.vacuna }}</strong>  |</p></li>
            </ul>
        </div>
    </div>
</div>
<hr>

{% endblock %}